### PR TITLE
Include additional parameters for consumption

### PR DESCRIPTION
**Pull request by alceasan**

### CODE REVIEW

**Review by JeroenEeuwes — COMMENTED** [review]
What kind of inverter do you have? I have a Solis 3P20-4G.

When I add your new parameters they are returned as "None". This gives problems later on to convert it to float. For example:

Login Succesfull on m.ginlong.com !
results from m.ginlong.com

Mon Aug 24 09:50:52 2020

DC_Voltage_PV1: 497.90
DC_Voltage_PV2: 422.80
DC_Current1: 3.60
DC_Current2: 3.70
AC_Voltage: 236.20
AC_Current: 4.40
AC_Power: 3150
AC_Frequency: 49.98
DC_Power_PV1: None
DC_Power_PV2: None
Power_Grid_Total_Power: None
Total_On_grid_Generation: None
Total_Energy_Purchased: None
Inverter_Temperature: 36.00
Daily_Generation: 2.70
Monthly_Generation: 2.5
Annual_Generation: 2.5
Total_Generation: 32.00
Generation_Last_Month: 0
Consumption_Power: None
Consumption_Energy: None
Daily_Energy_Used: None
Monthly_Energy_Used: None
Annual_Energy_Used: None

**Comment by alceasan** [comment]
My Solis inverter model is 1P5K-4G, and it's connected to an energy meter through modbus RTU RS485 so it can measure my home consumption.

Maybe these parameters can be a configurable option in case you have consumption info, or catch the exception in case they don't exist.

**Comment by craigcurtin-dev** [comment]
How are you guys going with getting this to run - i am having problems with urllib and urlib2 not wanting to install on Ubuntu VM 20.04.

What OS are you running it on ?

I have two solis 3P5k-4G inverters with an ADL3000 3phase energy monitor.

Craig

**Comment by alceasan** [comment]
I'm currently using this docker image based on this repository: https://hub.docker.com/r/fredericvl/ginlong-solis-scraper, which has support for ARM (I run it on a Rasp).

I manually included this changes on the Python sources and it has been working fine in my case for two months now.

**Comment by craigcurtin-dev** [comment]
Thanks for the quick reply on this.

I have pulled down the docker image and gotten it to run.

I have set all the environment variables and confirmed they are correct – but I keep getting a login failure – anyone else experienced this ?

I use a password manager (Lastpass) to generate all my passwords – hence they are complex – I have started up an incognito browser and logged in from there by pasting my password and it works fine. I have then pasted that into a file on Linux and passed that to the docker runtime – I can confirm (I use portainer) that the image has loaded the env-file fine and parsed all of the variables.

Any ideas ?

Craig

**Comment by craigcurtin-dev** [comment]
Worked it out - it does not like any embedded spaces/trailing formating - running now.

Now i just have to rework it to support multiple inverters and 3 phase !

Will report back progress as i go 

Thanks for the hint re the docker image

Craig

**Pull request closed without merging**
